const media = [
    {
        title: "ayKapHfJ7aj8t3l_j00mt0",
        place: "resort",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774351864/ayKapHfJ7aj8t3l_j00mt0.webp",
        type: "image",
        blurhash: "UwEyxokCM{s;?wozRjfk.8ozWBa#%gt7a#az",
        dimensions: "3084x4160",
    },
    {
        title: "xv874fepbvhpe7p7aose_aujolu",
        place: "resort",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774351864/xv874fepbvhpe7p7aose_aujolu.webp",
        type: "image",
        blurhash: "U68W?X00s%%O0L%2xbRj00^-I[IS~qD%M{-;",
        dimensions: "1599x1200",
    },
    {
        title: "yzrsmwyq5xm7lrwsgdot_hdt7ev",
        place: "resort",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774351864/yzrsmwyq5xm7lrwsgdot_hdt7ev.webp",
        type: "image",
        blurhash: "U58D|%0PtptS4mxts:oh00?cekM__4oLIsj]",
        dimensions: "1200x1599",
    },
    {
        title: "kdryfelfbjdss8bfgts9s_w4gmpl",
        place: "resort",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774351505/kdfryelfbjdss8bfgt9s_w4gmpl.webp",
        type: "image",
        blurhash: "",
        dimensions: "1599x1200",
    },
    {
        title: "ivgtwtkdeyyleeq51nma_k7qnma",
        place: "resort",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774351504/ivgtwtkdeyyleeq5lnma_k7qnma.webp",
        type: "image",
        blurhash: "",
        dimensions: "1599x1200",
    },

    {
        title: "a54jaxwgf2wemlfvk84e_b34fa9",
        place: "resort",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774351864/a54jaxwgf2wemlfvk84e_b34fa9.webp",
        type: "image",
        blurhash: "UiF6awRi%Lxt?dRjt7oftTRkRkWWtQbIRjaz",
        dimensions: "3024x4032",
    },

    {
        title: "t7vihhmtpm8du3z9yip2_uavmbm",
        place: "resort",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774351864/t7vihhmtpm8du3z9yip2_uavmbm.webp",
        type: "image",
        blurhash: "UNFYc700%g%1~pV@axo#s+o#M_jYMwtSIUe,",
        dimensions: "3024x4032",
    },
    {
        title: "awkxc7kf6d8fcivie8kd_moznov",
        place: "resort",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774351357/awkxc7kfd68fcivie8kd_moznov.webp",
        type: "image",
        blurhash: "",
        dimensions: "3024x4032",
    },
    {
        title: "igx00dkem2utjzgxofza_oq7kdu",
        place: "resort",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774351864/igx00dkem2utjzgxofza_oq7kdu.webp",
        type: "image",
        blurhash: "UDDdL9QyPbE101JM-q%2?K?sRRMzXONFXQX3",
        dimensions: "3024x4032",
    },
    {
        title: "uzv6qfv55ze8ek72u7mt_kb8bye",
        place: "resort",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774351864/uzv6qfv55ze8ek72u7mt_kb8bye.webp",
        type: "image",
        blurhash: "U8DSdf9v5E%L00_3%Loet-n$xCoJ~9IV9wxa",
        dimensions: "3024x4032",
    },
    {
        title: "pl1dbxcnl7hny1dovc04_mgvr5m",
        place: "resort",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774351864/pl1dbxcnl7hny1dovc04_mgvr5m.webp",
        type: "image",
        blurhash: "UmGb#EIUozkC_4M{offlxvflj?fkRkogaxf6",
        dimensions: "4032x3024",
    },
    {
        title: "iesxkze4fsogchwr5kgz_wduwxf",
        place: "resort",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774351864/iesxkze4fsogchwr5kgz_wduwxf.webp",
        type: "image",
        blurhash: "UbEylDWFWCR*.At7j[Rk%NxuWVRjM|t8kBRk",
        dimensions: "4032x3024",
    },
    {
        title: "v7vehuxd6pj1copzotz6_tstskq",
        place: "resort",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774351864/v7vehuxd6pj1copzotz6_tstskq.webp",
        type: "image",
        blurhash: "UWEfm0Rkj[xa.At7axt7%gt7M|fRIWxuRkjt",
        dimensions: "4032x3024",
    },
    {
        title: "pkizqccpumat2qrqducd_kxx9zz",
        place: "resort",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774351864/pkizqccpumat2qrqducd_kxx9zz.webp",
        type: "image",
        blurhash: "UXF$Y3E1Rjxu_4WARjj[%Nf$ayt7t7%Mt7j@",
        dimensions: "3024x4032",
    },
    {
        title: "IMG_9982_qae4vt",
        place: "resort",
        url: "https://res.cloudinary.com/dzovabwvn/video/upload/v1774350971/IMG_9982_qae4vt.mp4",
        type: "video",
        blurhash: "UeIFYAV[WBkC-tWBWBt6nYjZj[oM?uV[a#of",
        dimensions: "1080x1920",
    },
    {
        title: "IMG_9993_cq3ily",
        place: "resort",
        url: "https://res.cloudinary.com/dzovabwvn/video/upload/v1774350969/IMG_9993_cq3ily.mp4",
        type: "video",
        blurhash: "UmDmmrj=WBj]-@f4ayj].9odj[j[.8oyjuay",
        dimensions: "1080x1920",
    },
    {
        title: "IMG_9471_ujowtz",
        place: "resort",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774351864/IMG_9471_ujowtz.webp",
        type: "image",
        blurhash: "UEEfr.NHIT?aDGM$ais;-|xaxJfk?@ofWlt7",
        dimensions: "1170x1554",
    },
    {
        title: "Trust_for_quality_poster_jer32k",
        place: "winery",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774350601/Trust_for_quality_poster_ier32k.webp",
        type: "image",
        blurhash: "U9Gup:zADjxu}{%KEh9Z45c@5XwNtq-6Ng-=",
        dimensions: "875x1306",
    },
    {
        title: "paarl_port_9_poster_kn2c0x",
        place: "winery",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774350601/paarl_port_9_poster_knz0cx.webp",
        type: "image",
        blurhash: "",
        dimensions: "877x1285",
    },
    {
        title: "IMG_9470_kyubme",
        place: "resort",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774351864/IMG_9470_kyubme.webp",
        type: "image",
        blurhash: "UOB|Tp00%MRi~q9FxvNGxvM{oft7M{s:Rj%M",
        dimensions: "1170x777",
    },
    {
        title: "arena_castle_poster_ve56kh",
        place: "winery",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774351864/arena_castle_poster_ve56kh.webp",
        type: "image",
        blurhash: "UGI|Nx*hW90qrDV|xsoH05KiR:~2x[X2D,X9",
        dimensions: "884x1286",
    },
    {
        title: "teenager_poster_ttxw5p",
        place: "winery",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774351864/teenager_poster_ttxw5p.webp",
        type: "image",
        blurhash: "UTHBc2MIIV%MXA-QadNe_#%gt7rq|:Rlo#s*",
        dimensions: "841x1279",
    },
    {
        title: "aarya_dynasty_poster_qzhdin",
        place: "winery",
        url: "https://res.cloudinary.com/dzovabwvn/image/upload/v1774351864/aarya_dynasty_poster_qzhdin.webp",
        type: "image",
        blurhash: "UBF;fs_0Vt#Y1sM|NetP}SRkn%ov-z-mWERQ",
        dimensions: "883x1309",
    },
    // {
    //     title: "grapessy_2006_pfeqrb",
    //     place: "winery",
    //     url: "https://res.cloudinary.com/dzovabwvn/video/upload/v1759829731/grapessy_2006_pfeqrb.mp4",
    //     type: "video",
    //     blurhash: "",
    //     dimensions: "384x288",
    // },
];

export default media;
